Allow non admin users to upload image to glance
* Currently only users having admin related permission, has the
  ability to upload image to glance which later used to set Image/
  image_alt ref in tempest.conf. In order to make easier for non-admin
  user, this changes allow the same and if the user does not have
  permission to do the same, it will log an exception with the
  proper message as non-admin user can upload the image from CLI.

* Fixed set_default_tempest_options method for image as it is giving
  AttributeError: 'ImageService' object has no attribute 'image_path
  because image_path is set in set_image_preferences which is called
  after service_class in main.py which leads to the above error.

* Removed additional overrides image.http_image from roles

Change-Id: I3ab32b6c5628281f55193291cd367dcdb76a5571